### ISSUE TITLE
Links to pages are not rendered in the menu even with DISPLAY_PAGES_ON_MENU=True

### ISSUE THREAD

**Issue by jarobase** [nasskach/pelican-blueidea#5]
It seems that the pages are not visible on the menu. DISPLAY_PAGES_ON_MENU is set to true in pelicanconf.py. The pages are generated with THEME = 'notmyidea' but not with THEME = 'pelican-blueidea'.

Am I the only ne to encounter this bug?
Otherwise, the theme is working as expected.

**Comment by jarobase** [comment]
After some tests I finally managed to get rid of the bug. I simply copied the content of the `templates` folder of the default theme (notmyidea) in the the  `templates` folder of pelican-blueidea. It works. It seems that pelican updated the file `base.html`. Thanks again for this nice theme.

**Comment by maneesha** [comment]
I spent a long time troubleshooting this today using the same theme.  In case anyone else ever comes across this, here's my fix.  I'm not sure the entire `templates` folder needs to be replaced.  The template had an all uppercase variable name when it should have been lowercase.  In the file `templates/base.html` : 

The line ` {% for pg in PAGES | sort(attribute=PAGES_SORT_ATTRIBUTE) %}`  should be 
  `{% for pg in pages | sort(attribute=PAGES_SORT_ATTRIBUTE) %}`

**Comment by andreagrandi** [comment]
Thanks @maneesha I think it's the case. Pelican author mention it in the documentation http://docs.getpelican.com/en/stable/faq.html#since-i-upgraded-pelican-my-pages-are-no-longer-rendered the problem is that many of these themes are completely out of date / abandoned

**Comment by blueicefield** [comment]
I'm not using Pelican anymore but I will try time to fix this issue asap. Sorry for the delay.

**Comment by elbenfreund** [comment]
I can confirm the original issue and @maneesha s fix. Thanks everyone.

**Comment by nasskach** [comment]
Thanks everyone.

**Comment by aelmosalamy** [comment]
Thanks @maneesha I am almost 2 years later, and this helped me. Thanks alot!
